"""initial

Revision ID: fdcf4bf28bbd
Revises: 
Create Date: 2023-10-30 14:34:47.751448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcf4bf28bbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=False),
    sa.Column('payment_gate', sa.Enum('CENTER', name='paymentgateenum'), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'FULLY_PAID', 'PARTIALLY_PAID', 'REJECTED', 'DELETED', name='batchstatusenum'), nullable=False),
    sa.Column('batch_fee_percent', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_id'), 'batch', ['id'], unique=False)
    op.create_index(op.f('ix_batch_uid'), 'batch', ['uid'], unique=True)
    op.create_index(op.f('ix_batch_user_uid'), 'batch', ['user_uid'], unique=False)
    op.create_table('batchactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.Enum('CREATE', 'EDIT', 'CHANGE_STATUS', name='batchactivitytypeenum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'FULLY_PAID', 'PARTIALLY_PAID', 'REJECTED', 'DELETED', name='batchstatusenum'), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batchactivity_id'), 'batchactivity', ['id'], unique=False)
    op.create_index(op.f('ix_batchactivity_uid'), 'batchactivity', ['uid'], unique=True)
    op.create_table('batchpayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.Enum('CARD', 'BANK_ACCOUNT', 'CRYPT0', name='recipienttypeenum'), nullable=False),
    sa.Column('card_number', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'REJECTED', 'DELETED', 'VALIDATION_ERROR', 'PARTIALLY_PAID', name='batchpaymentstatusenum'), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('separated', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('card_holder', sa.String(), nullable=True),
    sa.Column('card_country', sa.String(), nullable=True),
    sa.Column('card_exp_month', sa.String(), nullable=True),
    sa.Column('card_exp_year', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.CheckConstraint('parent_id != id'),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['batchpayment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batchpayment_batch_id'), 'batchpayment', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batchpayment_id'), 'batchpayment', ['id'], unique=False)
    op.create_index(op.f('ix_batchpayment_uid'), 'batchpayment', ['uid'], unique=True)
    op.create_table('batchpaymentactivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.Enum('CREATE', 'EDIT', 'CHANGE_STATUS', name='batchpaymentactivitytypeenum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'REJECTED', 'DELETED', 'VALIDATION_ERROR', 'PARTIALLY_PAID', name='batchpaymentstatusenum'), nullable=False),
    sa.Column('batch_payment_id', sa.Integer(), nullable=False),
    sa.Column('batch_payment_parent_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_payment_id'], ['batchpayment.id'], ),
    sa.ForeignKeyConstraint(['batch_payment_parent_id'], ['batchpayment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batchpaymentactivity_id'), 'batchpaymentactivity', ['id'], unique=False)
    op.create_index(op.f('ix_batchpaymentactivity_uid'), 'batchpaymentactivity', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batchpaymentactivity_uid'), table_name='batchpaymentactivity')
    op.drop_index(op.f('ix_batchpaymentactivity_id'), table_name='batchpaymentactivity')
    op.drop_table('batchpaymentactivity')
    op.drop_index(op.f('ix_batchpayment_uid'), table_name='batchpayment')
    op.drop_index(op.f('ix_batchpayment_id'), table_name='batchpayment')
    op.drop_index(op.f('ix_batchpayment_batch_id'), table_name='batchpayment')
    op.drop_table('batchpayment')
    op.drop_index(op.f('ix_batchactivity_uid'), table_name='batchactivity')
    op.drop_index(op.f('ix_batchactivity_id'), table_name='batchactivity')
    op.drop_table('batchactivity')
    op.drop_index(op.f('ix_batch_user_uid'), table_name='batch')
    op.drop_index(op.f('ix_batch_uid'), table_name='batch')
    op.drop_index(op.f('ix_batch_id'), table_name='batch')
    op.drop_table('batch')
    # ### end Alembic commands ###
