version: '3.5'

services:

  bet_maker:
    build:
      context: ../
      dockerfile: bet_maker/Dockerfile
    image: bet_maker
    depends_on:
        - db
        - line_provider
    command: bash /app/start.sh
    restart: "no"
    env_file:
      - envs/test.env

  line_provider:
    build:
      context: ../
      dockerfile: line_provider/Dockerfile
    image: line_provider
    depends_on:
      - db
    restart: "no"
    command: bash /app/start.sh
    env_file:
      - envs/test.env

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8.16-management
    restart: always
    env_file:
      - envs/test.env


  db:
    hostname: db
    image: kartoza/postgis
    restart: always
    env_file:
      - envs/test.env